version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "Suar1301!!"
      MYSQL_DATABASE: "Employees"

  backend:
    build:
      context: ./studyingPortal
      dockerfile: Dockerfile   # Assuming your Dockerfile for the backend is named "Dockerfile"
    container_name: ems_backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/Employees"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "Suar1301!!"
