name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - feature/github-actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: frontend
        run: npm install --legacy-peer-deps

      - name: Build Angular project
        working-directory: frontend
        run: npm run build -- --configuration=production --output-path=docs --base-href=/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: frontend/docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
