name: Jekyll Pages

on:
  push:
    branches:
      - feature/github-actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Update to Node.js version 18

      - name: Install Angular CLI
        run: npm install -g @angular/cli@latest  # Install or update Angular CLI globally

      - name: Install dependencies
        working-directory: frontend
        run: npm install --legacy-peer-deps  # Install project dependencies
        
      - name: Build Angular project
        working-directory: frontend
        run: |
          npm install --force --legacy-peer-deps @angular/compiler@latest  # Install or update @angular/compiler
          npm run build -- --configuration=production --output-path=docs --base-href=/

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: frontend-build
          path: frontend/docs

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        id: download-artifact
        uses: actions/download-artifact@v2
        with:
          name: frontend-build  # Update to match the artifact name
          path: frontend/docs

      - name: Retry Deployment
        id: retry
        uses: octokit/request-action@v2.x
        with:
          route: PUT /repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/rerun
          mediaType: '{"previews":["ant-man"]}' # This is necessary for the rerun endpoint
        if: steps.download-artifact.outputs.artifacts_count == 0
        continue-on-error: true

      - name: Wait 10 seconds
        if: steps.download-artifact.outputs.artifacts_count == 0
        run: sleep 10

      - name: Deploy to GitHub Pages
        if: steps.download-artifact.outputs.artifacts_count > 0
        uses: actions/deploy-pages@v4
